/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package contadorcalorias;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonFeminino = new javax.swing.JRadioButton();
        buttonMasculino = new javax.swing.JRadioButton();
        campoNome = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        objPerda = new javax.swing.JRadioButton();
        objGanho = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tendenciaMagro = new javax.swing.JRadioButton();
        tendenciaGordo = new javax.swing.JRadioButton();
        tendenciaAtletico = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoBasal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoProteinaG = new javax.swing.JTextField();
        campoCarboG = new javax.swing.JTextField();
        campoGorduraG = new javax.swing.JTextField();
        campoProteinaK = new javax.swing.JTextField();
        campoCarboK = new javax.swing.JTextField();
        campoGorduraK = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonSubmeter = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        buttonCalcularLayne = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        buttonCalcularHarris = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        radioSedentario = new javax.swing.JRadioButton();
        radioLevemente = new javax.swing.JRadioButton();
        radioModeradamente = new javax.swing.JRadioButton();
        radioAltamente = new javax.swing.JRadioButton();
        radioExtremamente = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SEU PERFIL");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Sexo:");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Idade:");

        buttonGroup1.add(buttonFeminino);
        buttonFeminino.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonFeminino.setText("Feminino");

        buttonGroup1.add(buttonMasculino);
        buttonMasculino.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buttonMasculino.setText("Masculino");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Altura: ");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Objetivo:");

        buttonGroup3.add(objPerda);
        objPerda.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        objPerda.setText("Perda de Peso");

        buttonGroup3.add(objGanho);
        objGanho.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        objGanho.setText("Ganho Muscular");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel6.setText("Escolha uma única opção abaixo de acordo com seu corpo:");

        buttonGroup2.add(tendenciaMagro);
        tendenciaMagro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tendenciaMagro.setText("Tenho tendência a ser magro.");

        buttonGroup2.add(tendenciaGordo);
        tendenciaGordo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tendenciaGordo.setText("Tenho tendência a ser gordo.");

        buttonGroup2.add(tendenciaAtletico);
        tendenciaAtletico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tendenciaAtletico.setText("Tenho tendência a ser atlético.");

        jLabel8.setText(" ");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Seu metabolismo basal é:");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Quantidade de Proteína:");

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Quantidade de Carboidrato:");

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("Quantidade de Gordura:");

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel14.setText("Escolha uma única opção como objetivo final");

        buttonLimpar.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparMouseClicked(evt);
            }
        });

        buttonSubmeter.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        buttonSubmeter.setText("Salvar");
        buttonSubmeter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmeterMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setText("Peso:");

        buttonCalcularLayne.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        buttonCalcularLayne.setText("Layne Norton");
        buttonCalcularLayne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCalcularLayneMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Senha:");

        campoSenha.setText("jPasswordField1");
        campoSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoSenhaMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setText("g");

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setText("g");

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("g");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setText("Kcal");

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setText("Kcal");

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setText("Kcal");

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setText("Kcal");

        jLabel23.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel23.setText("Escolha o método de cálculo:");

        buttonCalcularHarris.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        buttonCalcularHarris.setText("Harris-Benedict");
        buttonCalcularHarris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCalcularHarrisMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel24.setText("Escolha seu nível de atividade física:");

        buttonGroup4.add(radioSedentario);
        radioSedentario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        radioSedentario.setText("Muito Sedentário – Pouca ou nenhuma atividade física.");

        buttonGroup4.add(radioLevemente);
        radioLevemente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        radioLevemente.setText("Levemente Ativo - Exercício leve 1 a 3 dias por semana.");

        buttonGroup4.add(radioModeradamente);
        radioModeradamente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        radioModeradamente.setText("Moderadamente Ativo - Ex. moderado 3 a 5 dias por semana.");

        buttonGroup4.add(radioAltamente);
        radioAltamente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        radioAltamente.setText("Altamente Ativo - Exercício pesado de 5 a 6 dias por semana.");

        buttonGroup4.add(radioExtremamente);
        radioExtremamente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        radioExtremamente.setText("Extremamente Ativo - Ex. pesado diário ou até 2 vezes por dia.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(campoCarboG, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(campoProteinaG, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(campoGorduraG, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(campoCarboK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel20))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(campoGorduraK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel21))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(campoProteinaK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel19))))
                                            .addComponent(buttonSubmeter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22))))
                                    .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonCalcularLayne)
                                    .addGap(75, 75, 75)
                                    .addComponent(buttonCalcularHarris))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tendenciaMagro)
                            .addComponent(tendenciaGordo)
                            .addComponent(tendenciaAtletico)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioLevemente)
                            .addComponent(radioModeradamente)
                            .addComponent(radioAltamente)
                            .addComponent(radioExtremamente)
                            .addComponent(radioSedentario)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(objPerda)
                                .addGap(25, 25, 25)
                                .addComponent(objGanho))
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoNome))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(10, 10, 10)
                                                .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonMasculino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonFeminino)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buttonMasculino)
                    .addComponent(buttonFeminino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(objPerda)
                    .addComponent(objGanho))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel8)
                        .addContainerGap(478, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tendenciaMagro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tendenciaGordo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tendenciaAtletico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(radioSedentario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioLevemente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioModeradamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAltamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioExtremamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCalcularLayne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCalcularHarris, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(campoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(campoProteinaG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoProteinaK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(campoCarboG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCarboK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(campoGorduraG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoGorduraK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSubmeter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparMouseClicked
        // TODO add your handling code here:
        campoAltura.setText("");
        campoBasal.setText("");
        campoCarboG.setText("");
        campoCarboK.setText("");
        campoGorduraG.setText("");
        campoGorduraK.setText("");
        campoIdade.setText("");
        campoNome.setText("");
        campoPeso.setText("");
        campoProteinaG.setText("");
        campoProteinaK.setText("");
        campoSenha.setText("");
        buttonFeminino.setSelected(false);
        buttonMasculino.setSelected(false);
        tendenciaGordo.setSelected(false);
        tendenciaMagro.setSelected(false);
        tendenciaAtletico.setSelected(false);
        objPerda.setSelected(false);
        objGanho.setSelected(false);
                
    }//GEN-LAST:event_buttonLimparMouseClicked

    private void buttonSubmeterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubmeterMouseClicked
        // TODO add your handling code here:
        
        // SALVAR PERFIL E INICIAR
        Altura = campoAltura.getText();
        Basal = campoBasal.getText();
        CarboG = campoCarboG.getText();
        CarboK = campoCarboK.getText();
        GorduraG = campoGorduraG.getText();
        GorduraK = campoGorduraK.getText();
        Idade = campoIdade.getText();
        Nome = campoNome.getText();
        Peso = campoPeso.getText();
        ProteinaG = campoProteinaG.getText();
        ProteinaK = campoProteinaK.getText();
        Senha = campoSenha.getText();
        Sexo = "";
        Tendencia = "";
        Objetivo = "";
        
        if (buttonMasculino.isSelected() == true){
            Sexo = "Masculino";
        }
        if (buttonFeminino.isSelected() == true){
            Sexo = "Feminino";
        }
        if (tendenciaMagro.isSelected() == true){
            Tendencia = "Magro";
        }
        if (tendenciaGordo.isSelected() == true){
            Tendencia = "Gordo";
        }
        if (tendenciaAtletico.isSelected() == true){
            Tendencia = "Atletico";
        }
        if (objGanho.isSelected() == true){
            Objetivo = "Ganho";
        }
        if (objPerda.isSelected() == true){
            Objetivo = "Perda";
        }
        
        if (radioSedentario.isSelected() == true){
            s_NivelAtividade = "Sedentário";
        }
        if (radioLevemente.isSelected() == true){
            s_NivelAtividade = "Levemente Ativo";
        }
        if (radioModeradamente.isSelected() == true){
            s_NivelAtividade = "Moderadamente Ativo";
        }
        if (radioAltamente.isSelected() == true){
            s_NivelAtividade = "Altamente Ativo";
        }
        if (radioExtremamente.isSelected() == true){
            s_NivelAtividade = "Extremamente Ativo";
        }   
       
        
        if(VerificaCampoEmBranco() == false){
            JOptionPane.showMessageDialog(this,
                "Existem campos em branco!!",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String s = "INSERT into Usuario values('"+Nome+"',"+Idade+",'"+Sexo+"',"+Altura+","+Peso+","
                    + "'"+Objetivo+"','"+Tendencia+"',"+Basal+","+ProteinaG+","+ProteinaK+","+CarboG+","+CarboK+","+GorduraG+","+GorduraK+",'"+Senha+"','"+Metodo+"', '"+s_NivelAtividade+"');";  

            System.out.println(s);
            try {
                insert(s);
                JOptionPane.showMessageDialog(this,
                "Cadastro criado com SUCESSO!!",
                "Error Message",
                JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,
                "Erro ao inserir cadastro!!",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
            }

             dispose();
        }
    }//GEN-LAST:event_buttonSubmeterMouseClicked

    @SuppressWarnings("empty-statement")
    private void buttonCalcularLayneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCalcularLayneMouseClicked
        // TODO add your handling code here:
        Metodo = "Layne Norton";
     
        // verificando se existem campos em branco
        if(VerificaCampoEmBranco() == false){
            JOptionPane.showMessageDialog(this,
                "Existem campos em branco!!",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            v_peso = Double.parseDouble(campoPeso.getText());

            // calculando a quantidade de calorias por dia
            if (tendenciaMagro.isSelected() == true){
                v_aux = 37 * v_peso;
            }
            if (tendenciaGordo.isSelected() == true){
                v_aux = 29 * v_peso;
            }
            if (tendenciaAtletico.isSelected() == true){
                v_aux = 33 * v_peso;
            }
            if (objGanho.isSelected() == true){
                v_basal = 1.1 * v_aux;
            }
            if (objPerda.isSelected() == true){
                v_basal = 0.85 * v_aux;
            }

            double p = Math.pow(10, 2), v = v_basal*p;
            v = Math.round(v);
            v = v/p;
            campoBasal.setText(""+v);

            // calculando a quantidade de proteina por dia. 2,5 GRAMAS POR KILO
            v_proteinaG = (v_peso * 2.5);

            double p0 = Math.pow(10, 2), v0 = v_proteinaG*p0;
            v0 = Math.round(v0);
            v0 = v0/p0;
            campoProteinaG.setText(""+v0);

            v_proteinaK = (v0 * 4.3);

            double p1 = Math.pow(10, 2), v1 = v_proteinaK*p1;
            v1 = Math.round(v1);
            v1 = v1/p1;
            campoProteinaK.setText(""+v1);

            // calculando a quantidade de gordura por dia. 20% DO VALOR TOTAL
            v_gorduraK = (0.2 * v_basal);

            double p3 = Math.pow(10, 2), v3 = v_gorduraK *p3;
            v3 = Math.round(v3);
            v3 = v3/p3;
            campoGorduraK.setText(""+v3);

            v_gorduraG = (v3 / 9.3);

            double p2 = Math.pow(10, 2), v2 = v_gorduraG *p2;
            v2 = Math.round(v2);
            v2 = v2/p2;
            campoGorduraG.setText(""+v2);


            // calculando a quantidade de carboidrato por dia. O RESTANTE.
            v_carboK = (v_basal - (v_proteinaK + v_gorduraK));
            double p5 = Math.pow(10, 2), v5 = v_carboK*p5;
            v5 = Math.round(v5);
            v5 = v5/p5;
            campoCarboK.setText(""+v5);

            v_carboG = (v5 / 4.1);

            double p4 = Math.pow(10, 2), v4 = v_carboG*p4;
            v4 = Math.round(v4);
            v4 = v4/p4;
            campoCarboG.setText(""+v4);
        }
        
    }//GEN-LAST:event_buttonCalcularLayneMouseClicked

    private void campoSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSenhaMouseClicked
        // TODO add your handling code here:
        campoSenha.setText("");
    }//GEN-LAST:event_campoSenhaMouseClicked

    private void buttonCalcularHarrisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCalcularHarrisMouseClicked
        Metodo = "Harris-Benedict";
        
        // verificando se existem campos em branco
        if( VerificaCampoEmBranco() == false){
            JOptionPane.showMessageDialog(this,
                "Existem campos em branco!!",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            // verificando nivel de atividade:    
            if (radioSedentario.isSelected() == true){
                NivelAtividade = 1.2;
            }
            if (radioLevemente.isSelected() == true){
                NivelAtividade = 1.37;
            }
            if (radioModeradamente.isSelected() == true){
                NivelAtividade = 1.55;
            }
            if (radioAltamente.isSelected() == true){
                NivelAtividade = 1.725;
            }
            if (radioExtremamente.isSelected() == true){
                NivelAtividade = 1.9;
            }   


            // verificando altura e idade e peso
            v_idade = Double.parseDouble(campoIdade.getText());
            v_peso = Double.parseDouble(campoPeso.getText()); 
            v_altura = Double.parseDouble(campoAltura.getText()); 
        
            if (buttonMasculino.isSelected() == true){
                Sexo = "Masculino";
                //Men	BMR = 88.362 + (13.397 x weight in kg) + (4.799 x height in cm) - (5.677 x age in years)

                // descrobrindo a taxa basal de acordo com a formula harris-benedict
                v_basal = 88.362 + (13.397 * v_peso) + (4.799 * v_altura) - (5.677 * v_idade);
                v_basal = v_basal * NivelAtividade;

                // taxa basal de acordo com o objetivo:
                if (objGanho.isSelected() == true){
                    v_basal = 1.1 * v_basal;
                }
                if (objPerda.isSelected() == true){
                    v_basal = 0.85 * v_basal;
                }

                // deixando com 2 casas decimais:
                double p = Math.pow(10, 2), v = v_basal*p;
                    v = Math.round(v);
                    v = v/p;
                campoBasal.setText(""+v);

                v_proteinaK = 0.30 * v_basal;
                double p1 = Math.pow(10, 2), v1 = v_proteinaK*p1;
                    v1 = Math.round(v1);
                    v1 = v1/p1;
                campoProteinaK.setText(""+v1);

                v_carboK = 0.50 * v_basal;
                double p2 = Math.pow(10, 2), v2 = v_carboK*p2;
                    v2 = Math.round(v2);
                    v2 = v2/p2;
                campoCarboK.setText(""+v2);

                v_gorduraK = 0.20 * v_basal;
                double p3 = Math.pow(10, 2), v3 = v_gorduraK*p3;
                    v3 = Math.round(v3);
                    v3 = v3/p3;
                campoGorduraK.setText(""+v3);
            
                v_proteinaG = v_proteinaK / 4.1;
                double p4 = Math.pow(10, 2), v4 = v_proteinaG*p4;
                    v4 = Math.round(v4);
                    v4 = v4/p4;
                campoProteinaG.setText(""+v4);

                v_carboG = v_carboK / 4.3;
                double p5 = Math.pow(10, 2), v5 = v_carboG*p5;
                    v5 = Math.round(v5);
                    v5 = v5/p5;
                campoCarboG.setText(""+v5);

                v_gorduraG = v_gorduraK / 9.3;
                double p6 = Math.pow(10, 2), v6 = v_gorduraG*p6;
                    v6 = Math.round(v6);
                    v6 = v6/p6;
                campoGorduraG.setText(""+v6);
            }
        
            if (buttonFeminino.isSelected() == true){
                Sexo = "Feminino";
                //Women	BMR = 447.593 + (9.247 x weight in kg) + (3.098 x height in cm) - (4.330 x age in years)
                v_basal = 447.593 + (9.247 * v_peso) + (3.098 * v_altura) - (4.330 * v_idade);
                v_basal = v_basal * NivelAtividade;

                 // taxa basal de acordo com o objetivo:
                if (objGanho.isSelected() == true){
                    v_basal = 1.1 * v_basal;
                }
                if (objPerda.isSelected() == true){
                    v_basal = 0.85 * v_basal;
                }

                double p = Math.pow(10, 2), v = v_basal*p;
                    v = Math.round(v);
                    v = v/p;
                campoBasal.setText(""+v);

                v_proteinaK = 0.30 * v_basal;
                double p1 = Math.pow(10, 2), v1 = v_proteinaK*p1;
                    v1 = Math.round(v1);
                    v1 = v1/p1;
                campoProteinaK.setText(""+v1);

                v_carboK = 0.50 * v_basal;
                double p2 = Math.pow(10, 2), v2 = v_carboK*p2;
                    v2 = Math.round(v2);
                    v2 = v2/p2;
                campoCarboK.setText(""+v2);

                v_gorduraK = 0.20 * v_basal;
                double p3 = Math.pow(10, 2), v3 = v_gorduraK*p3;
                    v3 = Math.round(v3);
                    v3 = v3/p3;
                campoGorduraK.setText(""+v3);

                v_proteinaG = v_proteinaK / 4.1;
                double p4 = Math.pow(10, 2), v4 = v_proteinaG*p4;
                    v4 = Math.round(v4);
                    v4 = v4/p4;
                campoProteinaG.setText(""+v4);
          
                v_carboG = v_carboK / 4.3;
                double p5 = Math.pow(10, 2), v5 = v_carboG*p5;
                    v5 = Math.round(v5);
                    v5 = v5/p5;
                campoCarboG.setText(""+v5);

                v_gorduraG = v_gorduraK / 9.3;
                double p6 = Math.pow(10, 2), v6 = v_gorduraG*p6;
                    v6 = Math.round(v6);
                    v6 = v6/p6;
                campoGorduraG.setText(""+v6);            
            }
        }
    }//GEN-LAST:event_buttonCalcularHarrisMouseClicked

    public static void insert(String S) throws SQLException { 
            //DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            
            Connection conn = DriverManager.getConnection( 
                                    "jdbc:postgresql://127.0.0.1:5432/Contador_Caloria", "postgres",
                                    "212889"); 
            conn.setAutoCommit(false); 
            Statement st = conn.createStatement(); 
            
            st.executeUpdate(S); 
            st.close(); 
            conn.commit(); 
            conn.close(); 
            System.out.println("Inserido com Sucesso!!!!");
    }
    
    public boolean VerificaCampoEmBranco(){
        Altura = campoAltura.getText();
        Idade = campoIdade.getText();
        Nome = campoNome.getText();
        Peso = campoPeso.getText();
        if (buttonMasculino.isSelected() == true){
            Sexo = "Masculino";}
        if (buttonFeminino.isSelected() == true){
            Sexo = "Feminino";}
        if (tendenciaMagro.isSelected() == true){
            Tendencia = "Magro";}
        if (tendenciaGordo.isSelected() == true){
            Tendencia = "Gordo";}
        if (tendenciaAtletico.isSelected() == true){
            Tendencia = "Atletico";}
        if (objGanho.isSelected() == true){
            Objetivo = "Ganho";}
        if (objPerda.isSelected() == true){
            Objetivo = "Perda";}   
        if (radioSedentario.isSelected() == true){
            s_NivelAtividade = "Sedentário";}
        if (radioLevemente.isSelected() == true){
            s_NivelAtividade = "Levemente Ativo";}
        if (radioModeradamente.isSelected() == true){
            s_NivelAtividade = "Moderadamente Ativo";}
        if (radioAltamente.isSelected() == true){
            s_NivelAtividade = "Altamente Ativo";}
        if (radioExtremamente.isSelected() == true){
            s_NivelAtividade = "Extremamente Ativo";} 
        // verificando se existem campos em branco
        if( campoIdade.getText() == null || campoAltura.getText() == null || campoNome.getText() == null || campoPeso.getText() == null || Sexo == null || Tendencia == null || Objetivo == null || s_NivelAtividade == null)
            return false;
        else
            return true;      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularHarris;
    private javax.swing.JButton buttonCalcularLayne;
    private javax.swing.JRadioButton buttonFeminino;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JRadioButton buttonMasculino;
    private javax.swing.JButton buttonSubmeter;
    private javax.swing.JTextField campoAltura;
    private javax.swing.JTextField campoBasal;
    private javax.swing.JTextField campoCarboG;
    private javax.swing.JTextField campoCarboK;
    private javax.swing.JTextField campoGorduraG;
    private javax.swing.JTextField campoGorduraK;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JTextField campoProteinaG;
    private javax.swing.JTextField campoProteinaK;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton objGanho;
    private javax.swing.JRadioButton objPerda;
    private javax.swing.JRadioButton radioAltamente;
    private javax.swing.JRadioButton radioExtremamente;
    private javax.swing.JRadioButton radioLevemente;
    private javax.swing.JRadioButton radioModeradamente;
    private javax.swing.JRadioButton radioSedentario;
    private javax.swing.JRadioButton tendenciaAtletico;
    private javax.swing.JRadioButton tendenciaGordo;
    private javax.swing.JRadioButton tendenciaMagro;
    // End of variables declaration//GEN-END:variables
    private Double v_peso = 0.0;
    private Double v_aux;
    private Double v_basal;
    private Double v_idade;
    private Double v_altura;
    private Double v_proteinaG = 0.0;
    private Double v_proteinaK = 0.0;
    private Double v_carboG = 0.0;
    private Double v_carboK = 0.0;
    private Double v_gorduraG = 0.0;
    private Double v_gorduraK = 0.0;
    String Altura;
    String Basal;
    String CarboG;
    String CarboK;
    String GorduraG;
    String GorduraK;
    String Idade;
    String Nome;
    String Peso;
    String ProteinaG;
    String ProteinaK;
    String Senha;
    String Sexo;
    String Tendencia;
    String Objetivo;
    private Double NivelAtividade;
    String s_NivelAtividade;
    String Metodo;
}

